### ISSUE TITLE
low-level API

### ISSUE THREAD

**Issue by kishankumar258** [deepgully/pyzil#4]
In the python file at tests/test_lowlevel_api.py, there is no script for creating a transaction.
Actually, I have created a local network of nodes and using pyzil client API as a means to have transactions between them.

**Comment by deepgully** [comment]
the API CreateTransaction requires signed txn, you can check the method "transfer" in account.py.

if you are working on a local API server, you can create a local chain:

```python
from pyzil.zilliqa import chain

local_chain = chain.BlockChain("http://127.0.0.1:4201/", version=65537, network_id=1)
chain.set_active_chain(local_chain) 
```
