### ISSUE TITLE
Fails to build -expected gmp.h not available

### ISSUE THREAD

**Issue by csajedi** [deepgully/pyzil#6]
I tried to pip install and to build from source, but I always get this output:

> gcc -pthread -B /home/tom/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Isrc/ -I/home/tom/miniconda3/include/python3.7m -c src/curveMath.c -o build/temp.linux-x86_64-3.7/src/curveMath.o -O2
    In file included from src/curveMath.c:1:0:
    src/curveMath.h:6:10: fatal error: gmp.h: No such file or directory
     #include <gmp.h>
              ^~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
> Command "/home/tom/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-iycz2l9f/fastecdsa/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4hlgv__x/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-iycz2l9f/fastecdsa/

is it possible to utilize this resource without gmp? I tried building it from source but had other issues that I am not motivated to fix.

**Comment by csajedi** [comment]
For anyone following along with this issue - you just need the lib-gmp headers for your distro. I got them through the ubuntu package manager: `sudo apt-get install libgmp-dev`

**Comment by pensebien** [comment]
This also resolved the issue for me.
