### ISSUE TITLE
GetDSBlockListing is not working

### ISSUE THREAD

**Issue by da-tai** [deepgully/pyzil#8]
Based on https://apidocs.zilliqa.com/?python#dsblocklisting , the function GETDSBLOCKLISTING is not working.

`pyzil.zilliqa.api.APIError: METHOD_NOT_FOUND: The method being requested is not available on this server`

**Comment by deepgully** [comment]
the apidoc is wrong, the API should be "DSBlockListing"

```python
from pyzil.zilliqa import chain
chain.set_active_chain(chain.MainNet)
print(chain.active_chain.api.DSBlockListing(1))
```
